### ISSUE TITLE
How to compile it with Java7 or Java8 ?

### ISSUE THREAD

**Issue by derjohn** [thinkberg/snipsnap#1]
It throws an error when I do "ant", snipsnap.org is down ATM .....

rgds,
j

**Comment by janni2** [comment]
Notes from my side.
Since the code itself can be build with Java and Ant, I gave it a try. Indeed Java is very backward compatible here, I managed to create jar files and war files, but then there were runtime issues:
a) via run.bat -> SnipSnapLauncher.java installs war on embedded Jetty, but the Jetty has trouble to find org/apache/xmlrpc/XmlRpcException
b) via standalone Tomcat (8.5), upload war -> ClassNotFoundException: org.apache.jasper.runtime.JspException - which is
 actually true with the delivered jasper runtime of the Tomcat vs the compiled javax.servlet.jar

I see two options to bring it to life again (I'm curios, what the software actually does)
a) Docker or VM with very old Java and Tomcat (guessing by year, we live in the Servlet 2.5 world here with JavaEE5 and Tomcat 6)
b) Start a Gradle JSP project, have a look how it works and migrate the Ant script to Gradle to handle (or better say, upgrade dependencies)

**Comment by janni2** [comment]
Got it running: https://github.com/janni2/snipsnap

Still not knowing, which 'killer-features' there are :D

**Comment by thinkberg** [comment]
Very nice. The strange address is probably the code that tries to detect host name and port behind a proxy (https://github.com/thinkberg/snipsnap/blob/f72288635c3f4215665f65e162061f50f43e2bd7/src/apps/default/WEB-INF/classes/i18n/setup_en.properties#L282)

As for the killer-features, its a wiki that is simple to extend from within the wiki. As an admin you can add wiki pages that are executed as code. I probably even forgot what nuggets there were in the code ;-)
